[package]
name = "better-mods-manager"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "better-mods-manager"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["dialog-open", "dialog-save", "fs-all", "path-all", "window-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2"
fs_extra = "1"
anyhow = "1"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.6"
