[package]
name = "better-mods-manager"
version = "0.9.11"
edition = "2021"

[[bin]]
name = "better-mods-manager"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "1", features = [] }
chrono = "0.4"
embed-resource = "2"

[dependencies]
tauri = { version = "1", features = [ "cli", "dialog-message", "dialog-confirm", "dialog-ask", "protocol-asset", "custom-protocol", "notification-all", "dialog-open", "dialog-save", "fs-all", "path-all", "window-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2"
fs_extra = "1"
anyhow = "1"
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls", "stream"] }
zip = { version = "0.6", features = ["deflate"] }
lazy_static = "1.4"
backtrace = "0.3"
sysinfo = "0.30"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
discord-rich-presence = "0.2.4"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
futures = "0.3"
sha2 = "0.10.9"
warp = "0.3"
local-ip-address = "0.6"
igd = "0.12"
regex = "1"
bytes = "1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
hex = "0.4"
[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = ["Win32_System_Threading"] }
rand = "0.8"
tokio-util = { version = "0.7", features = ["io"] }
windows-sys = { version = "0.45", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse"] }
percent-encoding = "2.3"
tempfile = "3"
base64 = "0.21"
winreg = "0.52"
rayon = "1.8"
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
jwalk = "0.8"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# it is the default for `tauri build`
custom-protocol = [ "tauri/custom-protocol" ]
