"""Write src-tauri/tests/laya_golden.json: the Python reference the Rust engine is tested against.

What it records, for a fixed multilingual subset of the measurement set (scripts/laya/samples.py):
  * every text the package tokenizes (the state, each question head, each option), with its ids
    -- the Rust test answers the engine's tokenizer calls from this map, so it proves Rust asks
    for exactly the same pieces, without shipping the 34 MB tokenizer.json in git;
  * the rows `laya.onnx_agent.ONNXAgent._encode_state` builds (ids + marker positions);
  * the probabilities ONNXAgent's own decode gives, unrounded, on the pinned int8 pack.

Usage (from the repo root, in a venv with `pip install "laya[onnx]==0.3.21"`):
    python scripts/laya/make_golden.py <checkpoint dir> <pack dir>
<checkpoint dir> holds rl_agent_config.json, tokenizer/ and encoder/ of the pinned revision;
<pack dir> is an unpacked model pack (laya.onnx).
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from samples import golden_items  # noqa: E402

os.environ.setdefault("HF_HUB_OFFLINE", "1")

import laya.common as common  # noqa: E402
import laya.onnx_agent as onnx_agent  # noqa: E402
from laya.onnx_agent import ONNXAgent  # noqa: E402

ckpt, pack = sys.argv[1], sys.argv[2]
out_path = sys.argv[3] if len(sys.argv) > 3 else os.path.join("src-tauri", "tests", "laya_golden.json")

agent = ONNXAgent(ckpt, onnx_path=os.path.join(pack, "laya.onnx"))
tok = agent.tok

# Record every text the package tokenizes, with its UNtruncated ids (Rust truncates itself).
pieces = {}
_orig = common.encode_text


def recording(t, text, **kw):
    pieces[text] = list(t(text, add_special_tokens=False)["input_ids"])
    return _orig(t, text, **kw)


common.encode_text = recording
onnx_agent.encode_text = recording

items_out = []
for it in golden_items():
    state, questions = it["state"], it["questions"]
    ids = list(questions.keys())
    internal = {qid: agent._to_internal(questions[qid]) for qid in ids}
    rows = agent._encode_state(state, ids, internal, agent.cfg["max_len"], agent.cfg["head_max_len"])
    b = common.collate_items([rows], tok.pad_token_id)
    logits, act = agent.session.run(["logits", "act_logits"], {
        "input_ids": b["input_ids"].numpy().astype(np.int64),
        "attention_mask": b["attention_mask"].numpy().astype(np.int64),
        "marker_pos": b["marker_pos"].numpy().astype(np.int64),
        "marker_mask": b["marker_mask"].numpy().astype(bool),
        "qtype": b["qtype"].numpy().astype(np.int64),
    })
    # The package's own answer, rounded, as a cross-check of the raw decode below.
    ref = agent.predict(state, questions)["answers"]
    out_rows, out_qs = [], []
    for r, qid in enumerate(ids):
        q = questions[qid]
        k = len(rows[r]["markers"])
        qt = common.QTYPES[q["type"]]
        t = agent.temperature_by_options.get(common.temp_bucket(qt, k), agent.temperature[qt])
        z = logits[r, :k].astype(np.float64) / t
        p = np.exp(z - z.max())
        p = p / p.sum()
        if q["type"] == "noul":
            assert abs(round(float(p[1]), 4) - ref[qid]["noul"]) < 1e-4
        else:
            assert list(q["criteria"].keys())[int(p.argmax())] == ref[qid]["choice"]
        out_rows.append({"ids": [int(x) for x in rows[r]["ids"]], "markers": [int(m) for m in rows[r]["markers"]],
                         "probs": [float(x) for x in p]})
        crit = q.get("criteria")
        out_qs.append({"id": qid, "type": q["type"], "instructions": q["instructions"],
                       "criteria": [[k2, v2 or ""] for k2, v2 in crit.items()] if isinstance(crit, dict) else None})
    items_out.append({"id": it["id"], "lang": it["lang"], "text": state["body"], "questions": out_qs, "rows": out_rows})

cfg = json.load(open(os.path.join(ckpt, "rl_agent_config.json"), encoding="utf-8"))
doc = {
    "note": "Generated by scripts/laya/make_golden.py from laya 0.3.21 ONNXAgent on the pinned int8 pack. Do not edit.",
    "config": {k: cfg[k] for k in ("max_len", "head_max_len", "temperature", "temperature_by_options")},
    "pieces": pieces,
    "items": items_out,
}
with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    json.dump(doc, f, ensure_ascii=False, separators=(",", ":"))
print("wrote", out_path, "items", len(items_out), "rows", sum(len(i["rows"]) for i in items_out),
      "pieces", len(pieces), "bytes", os.path.getsize(out_path))
