//! « Ask Laya » — ask BMM a question in plain words and get back the documentation, the setting,
//! the command, the mods or the FILES that answer it. Offline, and never invented text.
//!
//! Mounted twice, like `ai_core`: by the app (`commands::ask_core`, the Ctrl+K « Ask Laya »
//! dialog, the docs hub and the library search) and by the CLI/MCP binary (`bmm ai-ask`,
//! `bmm_ai_ask`). Only external crates, `ai_core` and `ai_laya` (both mounted in both) are used.
//!
//! ## How an answer is found
//!
//! 1. **Deterministic retrieval first.** A BM25 index over what BMM knows: the bundled BMM Docs
//!    pages cut at their headings, the docs hub articles and the palette's commands (all three in
//!    `ask_index.gen.json`, generated by `scripts/gen-ask-index.mjs`), the Settings cards the app
//!    adds at run time, the user's mods (name, description, tags) and profiles. File questions
//!    (« quel mod modifie engine.ogg ? ») and conflict questions (« quels mods sont en conflit ? »)
//!    are answered from the mods' own file lists — exact, not ranked text.
//! 2. **Laya ranks** — only when the embedded model is installed and the AI master switch
//!    allows it: one `choice` question picks the best of the top candidates (+ « none of
//!    these »), and the retrieval score and Laya's vote are averaged; without Laya, the retrieval
//!    order stands. The intent (documentation / setting / files / conflicts / mods / command) is
//!    routed by keyword rules: a Laya intent question was measured and lost to them (19/36
//!    against 27/36, `ai_eval::measure_ask`), so it is not asked.
//! 3. **Display, never generate.** The result is a list of things that exist — a doc section with
//!    its own text as the snippet, a setting to jump to, a command to run, mods and the files they
//!    provide — each with an action. Nothing is written by a model.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;
use std::time::Instant;

use crate::commands::ai_core::{self, LayaQuestion, LocalModel};
use crate::commands::ai_laya as L;

/// Characters of a question read at all.
pub const MAX_QUESTION: usize = 300;
/// Candidates Laya is asked to choose among (+ « none »).
pub const RERANK_K: usize = 6;
/// Results returned by default.
pub const DEFAULT_LIMIT: usize = 8;

// ─────────────────────────────────────────────────────────────────────────────
// What can be found
// ─────────────────────────────────────────────────────────────────────────────

/// One thing an answer can point at. `k`: "doc" | "article" | "command" | "setting" | "mod" |
/// "profile". `a` is the action the UI performs (`{page, anchor}`, `{article}`, `{command}`,
/// `{setting}`, `{mod}`, `{profile}`).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Entry {
    pub k: String,
    #[serde(default)]
    pub lang: String,
    pub id: String,
    pub t: String,
    #[serde(default)]
    pub x: String,
    #[serde(default)]
    pub kw: String,
    #[serde(default)]
    pub a: Value,
}

#[derive(Deserialize)]
struct IndexFile {
    entries: Vec<Entry>,
}

const BUILTIN: &str = include_str!("ask_index.gen.json");

/// The documentation, articles and commands compiled into this binary.
pub fn builtin() -> &'static [Entry] {
    static B: OnceLock<Vec<Entry>> = OnceLock::new();
    B.get_or_init(|| serde_json::from_str::<IndexFile>(BUILTIN).map(|f| f.entries).unwrap_or_default())
}

/// A mod as Ask sees it: what it is called and says, whether it is enabled in the active
/// profile, and the files it provides (relative paths, as BMM's scan cache holds them).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModInfo {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub files: Vec<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProfileInfo {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub game: String,
    #[serde(default)]
    pub active_count: usize,
}

#[derive(Debug, Clone, Default)]
pub struct Library {
    pub mods: Vec<ModInfo>,
    pub profiles: Vec<ProfileInfo>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Words
// ─────────────────────────────────────────────────────────────────────────────

const STOP: &[&str] = &[
    // EN
    "the", "a", "an", "and", "or", "of", "to", "in", "on", "for", "with", "is", "are", "be", "it", "this", "that", "what", "which", "how", "do",
    "does", "can", "i", "my", "me", "you", "your", "there", "any", "from", "by", "as", "at", "if", "when", "where", "why", "who", "should",
    // FR
    "le", "la", "les", "un", "une", "des", "du", "de", "d", "l", "et", "ou", "a", "au", "aux", "en", "dans", "sur", "pour", "avec", "est",
    "sont", "c", "ce", "cet", "cette", "ces", "quoi", "que", "qui", "quel", "quels", "quelle", "quelles", "comment", "pourquoi", "je", "j",
    "mon", "ma", "mes", "tu", "ton", "ta", "tes", "vous", "votre", "vos", "il", "elle", "on", "se", "s", "y", "ne", "pas", "qu", "est-ce",
    "fait", "faire", "t",
];

/// Folded words, stop-words out, plural `s` stripped from long words (« conflits » = « conflit »).
pub fn terms(s: &str) -> Vec<String> {
    L::words(s)
        .into_iter()
        .flat_map(|w| {
            // « engine.ogg » stays whole AND gives « engine » + « ogg »; « Saved-Games » likewise.
            let mut v = vec![w.clone()];
            if w.contains('.') || w.contains('-') {
                v.extend(w.split(['.', '-']).filter(|p| p.chars().count() >= 2).map(str::to_string));
            }
            v
        })
        .filter(|w| !STOP.contains(&w.as_str()))
        .map(|w| if w.chars().count() > 4 && w.ends_with('s') && !w.ends_with("ss") { w[..w.len() - 1].to_string() } else { w })
        .collect()
}

// ─────────────────────────────────────────────────────────────────────────────
// BM25
// ─────────────────────────────────────────────────────────────────────────────

pub struct Index {
    entries: Vec<Entry>,
    docs: Vec<HashMap<String, f64>>,
    titles: Vec<HashSet<String>>,
    len: Vec<f64>,
    df: HashMap<String, usize>,
    avg: f64,
}

impl Index {
    /// Title words count three times, keywords twice, the text once.
    pub fn build(entries: Vec<Entry>) -> Index {
        let mut docs = Vec::with_capacity(entries.len());
        let mut titles = Vec::with_capacity(entries.len());
        let mut len = Vec::with_capacity(entries.len());
        let mut df: HashMap<String, usize> = HashMap::new();
        for e in &entries {
            let mut tf: HashMap<String, f64> = HashMap::new();
            for (text, w) in [(&e.t, 3.0), (&e.kw, 2.0), (&e.x, 1.0)] {
                for t in terms(text) {
                    *tf.entry(t).or_insert(0.0) += w;
                }
            }
            for t in tf.keys() {
                *df.entry(t.clone()).or_insert(0) += 1;
            }
            len.push(tf.values().sum::<f64>().max(1.0));
            docs.push(tf);
            titles.push(terms(&e.t).into_iter().collect());
        }
        let avg = if len.is_empty() { 1.0 } else { len.iter().sum::<f64>() / len.len() as f64 };
        Index { entries, docs, titles, len, df, avg }
    }

    pub fn entry(&self, i: usize) -> &Entry {
        &self.entries[i]
    }

    /// Okapi BM25 (k1 1.2, b 0.75), plus a small prefix match so « activ » finds « activer », and
    /// a bonus for the share of the question's words that are in the TITLE: « export mod list »
    /// is the command called « Export mod list », not the long page that says « export » ten times.
    pub fn search(&self, q: &str, filter: &dyn Fn(&Entry) -> bool) -> Vec<(usize, f64)> {
        let qt: Vec<String> = {
            let mut v = terms(q);
            v.dedup();
            v
        };
        if qt.is_empty() {
            return Vec::new();
        }
        let n = self.entries.len() as f64;
        let (k1, b) = (1.2, 0.75);
        let mut out = Vec::new();
        for (i, tf) in self.docs.iter().enumerate() {
            if !filter(&self.entries[i]) {
                continue;
            }
            let mut s = 0.0;
            for t in &qt {
                let f = tf.get(t).copied().or_else(|| {
                    if t.chars().count() >= 5 {
                        tf.iter().filter(|(k, _)| k.starts_with(t.as_str())).map(|(_, v)| *v * 0.6).fold(None, |a: Option<f64>, v| Some(a.map_or(v, |a| a.max(v))))
                    } else {
                        None
                    }
                });
                if let Some(f) = f {
                    let df = self.df.get(t).copied().unwrap_or(1) as f64;
                    let idf = ((n - df + 0.5) / (df + 0.5) + 1.0).ln();
                    s += idf * f * (k1 + 1.0) / (f + k1 * (1.0 - b + b * self.len[i] / self.avg));
                }
            }
            if s > 0.0 {
                let cov = qt.iter().filter(|t| self.titles[i].contains(*t)).count() as f64 / qt.len() as f64;
                out.push((i, s * (1.0 + 0.8 * cov)));
            }
        }
        out.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        out
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Intent
// ─────────────────────────────────────────────────────────────────────────────

/// A file-looking word: « engine.ogg », « Mods/aircraft », « textures\\a.dds ».
fn file_terms(q: &str) -> Vec<String> {
    q.split_whitespace()
        .map(|w| w.trim_matches(|c: char| "«»\"'?!,;:()[]".contains(c)))
        .filter(|w| {
            let has_ext = w.rsplit_once('.').map(|(a, e)| !a.is_empty() && (2..=5).contains(&e.len()) && e.chars().all(|c| c.is_ascii_alphanumeric())).unwrap_or(false);
            has_ext || w.contains('/') || w.contains('\\')
        })
        .map(|w| w.replace('\\', "/").to_lowercase())
        .collect()
}

/// The keyword rules: a prior per intent (0..1) and whether it is decisive on its own.
pub fn intent_rules(q: &str) -> (Vec<(String, f64)>, bool) {
    let f = format!(" {} ", L::fold(q));
    let has = |ws: &[&str]| ws.iter().any(|w| f.contains(w));
    let files = !file_terms(q).is_empty();
    let conflict = has(&["conflit", "conflict", "overlap", "ecrase", "overwrit", "chevauch", "se battent", "fight over", "clash"]);
    let which_mod = has(&["quel mod", "quels mod", "which mod", "what mod", "qui modifie", "modifie ", "modifies", "replace", "remplace", "provid", "fournit", "touch"]);
    let setting = has(&["reglage", "parametre", "setting", "option", "activer", "desactiver", "turn on", "turn off", "enable ", "disable ", "configur", "changer "]);
    let command = has(&[" ouvr", " open ", " lance", " run ", " export", " import", " scan", " verifi", " verify", " go to", " aller "]);
    let docs = has(&["c'est quoi", "c est quoi", "what is", "what's", "what are", "how ", "comment", "pourquoi", "why", "explain", "explique", "difference", "a quoi sert", "à quoi sert"]);
    let mods = has(&[" mes mods", " my mods", " installed", " installe", " profil", " profile"]);
    let mut p = vec![("docs".to_string(), 0.3), ("setting".to_string(), 0.1), ("files".to_string(), 0.05), ("conflicts".to_string(), 0.05), ("mods".to_string(), 0.1), ("command".to_string(), 0.1)];
    let mut bump = |k: &str, v: f64| {
        if let Some(x) = p.iter_mut().find(|(n, _)| n == k) {
            x.1 += v;
        }
    };
    if conflict {
        bump("conflicts", 0.8);
    }
    if files {
        bump("files", if which_mod { 0.9 } else { 0.6 });
    } else if which_mod && has(&["fichier", " file"]) {
        bump("files", 0.6);
    }
    if setting {
        bump("setting", 0.4);
    }
    if command {
        bump("command", 0.4);
    }
    if docs {
        bump("docs", 0.4);
    }
    if mods {
        bump("mods", 0.3);
    }
    let total: f64 = p.iter().map(|x| x.1).sum();
    for x in p.iter_mut() {
        x.1 /= total;
    }
    p.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    let decisive = conflict || files;
    (p, decisive)
}

// ─────────────────────────────────────────────────────────────────────────────
// Files and conflicts — exact answers from the mods' file lists
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct FileHit {
    pub mod_id: String,
    pub mod_name: String,
    pub enabled: bool,
    /// The matching files (at most 10) and how many matched in all.
    pub files: Vec<String>,
    pub total: usize,
}

fn norm_path(p: &str) -> String {
    p.replace('\\', "/").to_lowercase()
}

/// Which mods provide a file matching any of `needles` (a name, a path suffix, a folder).
pub fn find_files(lib: &Library, needles: &[String]) -> Vec<FileHit> {
    let mut out = Vec::new();
    for m in &lib.mods {
        let mut hits: Vec<String> = Vec::new();
        let mut total = 0usize;
        for f in &m.files {
            let nf = norm_path(f);
            let name = nf.rsplit('/').next().unwrap_or(&nf);
            if needles.iter().any(|n| name == n.as_str() || nf.ends_with(&format!("/{}", n)) || nf == *n || (n.contains('/') && nf.contains(n.as_str()))) {
                total += 1;
                if hits.len() < 10 {
                    hits.push(f.replace('\\', "/"));
                }
            }
        }
        if total > 0 {
            out.push(FileHit { mod_id: m.id.clone(), mod_name: m.name.clone(), enabled: m.enabled, files: hits, total });
        }
    }
    out.sort_by(|a, b| b.enabled.cmp(&a.enabled).then(b.total.cmp(&a.total)).then(a.mod_name.cmp(&b.mod_name)));
    out
}

#[derive(Debug, Clone, Serialize)]
pub struct ConflictHit {
    pub a_id: String,
    pub a_name: String,
    pub b_id: String,
    pub b_name: String,
    pub both_enabled: bool,
    pub count: usize,
    pub sample: Vec<String>,
}

/// Pairs of mods that provide the same file (case-insensitive path), both-enabled pairs first.
/// `only` restricts to pairs involving these mod ids.
pub fn find_conflicts(lib: &Library, only: &HashSet<String>, limit: usize) -> Vec<ConflictHit> {
    let mut by_file: HashMap<String, Vec<usize>> = HashMap::new();
    for (i, m) in lib.mods.iter().enumerate() {
        let mut seen: HashSet<String> = HashSet::new();
        for f in &m.files {
            let nf = norm_path(f);
            if seen.insert(nf.clone()) {
                by_file.entry(nf).or_default().push(i);
            }
        }
    }
    let mut pairs: HashMap<(usize, usize), (usize, Vec<String>)> = HashMap::new();
    for (f, ms) in by_file {
        if ms.len() < 2 || ms.len() > 16 {
            // A file every mod ships (a readme) says nothing about a conflict between two.
            continue;
        }
        for x in 0..ms.len() {
            for y in (x + 1)..ms.len() {
                let e = pairs.entry((ms[x], ms[y])).or_insert((0, Vec::new()));
                e.0 += 1;
                if e.1.len() < 5 {
                    e.1.push(f.clone());
                }
            }
        }
    }
    let ignore = |f: &str| {
        let n = f.rsplit('/').next().unwrap_or(f);
        n.starts_with("readme") || n.starts_with("license") || n.starts_with("changelog") || n == "entry.lua" || n == "description.lua" || n.ends_with(".txt") || n.ends_with(".md")
    };
    let mut out: Vec<ConflictHit> = pairs
        .into_iter()
        .filter_map(|((a, b), (count, mut sample))| {
            sample.retain(|f| !ignore(f));
            if sample.is_empty() {
                return None;
            }
            let (ma, mb) = (&lib.mods[a], &lib.mods[b]);
            if !only.is_empty() && !only.contains(&ma.id) && !only.contains(&mb.id) {
                return None;
            }
            sample.sort();
            Some(ConflictHit { a_id: ma.id.clone(), a_name: ma.name.clone(), b_id: mb.id.clone(), b_name: mb.name.clone(), both_enabled: ma.enabled && mb.enabled, count, sample })
        })
        .collect();
    out.sort_by(|x, y| y.both_enabled.cmp(&x.both_enabled).then(y.count.cmp(&x.count)).then(x.a_name.cmp(&y.a_name)));
    out.truncate(limit);
    out
}

// ─────────────────────────────────────────────────────────────────────────────
// The answer
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Deserialize, Default)]
#[serde(default)]
pub struct Request {
    pub question: String,
    /// "en" | "fr": which language to show a bilingual entry in (both are searched).
    pub lang: String,
    /// "all" | "docs" | "mods".
    pub scope: String,
    pub limit: usize,
    /// Entries only the app knows (its Settings cards), added to the index for this question.
    pub extra: Vec<Entry>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Hit {
    pub kind: String,
    pub id: String,
    pub title: String,
    pub snippet: String,
    /// Final score, 0..1 (retrieval, averaged with Laya's vote when it was asked).
    pub score: f64,
    /// Laya's own probability for this candidate, when asked.
    pub laya: Option<f64>,
    pub action: Value,
}

#[derive(Debug, Clone, Serialize)]
pub struct Answer {
    pub question: String,
    pub intent: String,
    pub intent_p: f64,
    /// How the intent was decided ("rules").
    pub routed_by: String,
    pub hits: Vec<Hit>,
    pub files: Vec<FileHit>,
    pub conflicts: Vec<ConflictHit>,
    /// Laya ranked the candidates (false: retrieval only — AI off, no model, or not needed).
    pub laya: bool,
    /// Laya said none of the candidates answers the question.
    pub low_confidence: bool,
    pub notes: Vec<String>,
    pub ms: u64,
}

fn snippet(x: &str, q: &[String], n: usize) -> String {
    // The sentence that holds the most query words, else the start.
    let sentences: Vec<&str> = x.split_inclusive(['.', '!', '?', ':']).collect();
    let best = sentences
        .iter()
        .enumerate()
        .map(|(i, s)| (i, terms(s).iter().filter(|t| q.contains(t)).count()))
        .max_by(|a, b| a.1.cmp(&b.1).then(b.0.cmp(&a.0)))
        .map(|(i, c)| if c > 0 { i } else { 0 })
        .unwrap_or(0);
    let s: String = sentences[best.min(sentences.len().saturating_sub(1))..].concat();
    let s = s.trim();
    if s.chars().count() <= n { s.to_string() } else { format!("{}…", s.chars().take(n).collect::<String>().trim_end()) }
}

fn mod_entries(lib: &Library) -> Vec<Entry> {
    let mut v: Vec<Entry> = lib
        .mods
        .iter()
        .map(|m| Entry { k: "mod".into(), lang: String::new(), id: format!("mod:{}", m.id), t: m.name.clone(), x: m.description.chars().take(600).collect(), kw: m.tags.join(" "), a: json!({ "mod": m.id, "name": m.name }) })
        .collect();
    v.extend(lib.profiles.iter().map(|p| Entry { k: "profile".into(), lang: String::new(), id: format!("profile:{}", p.id), t: p.name.clone(), x: format!("{} · {} mods", p.game, p.active_count), kw: "profile profil".into(), a: json!({ "profile": p.id }) }));
    v
}

fn kind_fits(intent: &str, k: &str) -> f64 {
    match (intent, k) {
        ("docs", "doc") | ("docs", "article") => 1.0,
        ("setting", "setting") => 1.0,
        ("setting", "doc") | ("setting", "article") => 0.7,
        ("command", "command") => 1.0,
        ("command", "setting") => 0.8,
        ("mods", "mod") | ("mods", "profile") => 1.0,
        ("files", "mod") | ("conflicts", "mod") => 0.8,
        (_, "command") => 0.55,
        (_, "setting") => 0.7,
        (_, "mod") | (_, "profile") => 0.6,
        _ => 0.8,
    }
}

/// Answer a question. `model` is the embedded Laya engine when the caller's gate allows it
/// (`None` = retrieval only, which is always available, offline, with AI off).
#[cfg_attr(not(test), allow(dead_code))]
pub fn answer(req: &Request, lib: &Library, model: Option<&dyn LocalModel>) -> Answer {
    answer_tuned(req, lib, model, &crate::commands::ai_tuning::builtin(crate::commands::ai_tuning::Area::Ask))
}

/// [`answer`] with the user's answer settings for « Ask Laya » (« Réglages des réponses »):
/// `top_k` = how many results Laya compares, the temperature, and when the answer reads as
/// unsure (`low_confidence`): Laya's « none » first, then the threshold and the margin on its
/// best candidate. « Équilibré » is exactly [`answer`] as it was.
pub fn answer_tuned(req: &Request, lib: &Library, model: Option<&dyn LocalModel>, tune: &crate::commands::ai_tuning::Tuning) -> Answer {
    let started = Instant::now();
    let question: String = req.question.trim().chars().take(MAX_QUESTION).collect();
    let limit = if req.limit == 0 { DEFAULT_LIMIT } else { req.limit.min(30) };
    let lang = if req.lang == "fr" { "fr" } else { "en" };
    let scope = req.scope.as_str();
    let mut notes: Vec<String> = Vec::new();
    let qt = terms(&question);

    // Intent: keyword rules. A Laya « what does the user want » question was measured and
    // dropped: it routed 19 of 36 benchmark questions right, the rules 27 (ai_eval::measure_ask).
    let (intents, _decisive) = intent_rules(&question);
    let routed_by = "rules".to_string();
    let mut laya_used = false;
    let (intent, intent_p) = if scope == "mods" { ("mods".to_string(), 1.0) } else { intents[0].clone() };

    // Exact answers.
    let mut files = Vec::new();
    let mut conflicts = Vec::new();
    let mods_named: Vec<String> = {
        // A mod named in the question (« conflits de Better Rifles ? »).
        let fq = L::fold(&question);
        lib.mods.iter().filter(|m| m.name.chars().count() >= 4 && fq.contains(&L::fold(&m.name))).map(|m| m.id.clone()).collect()
    };
    if intent == "files" || !file_terms(&question).is_empty() {
        let mut needles = file_terms(&question);
        if needles.is_empty() {
            // « quel mod modifie les sons du moteur ? » — no file name: search the words in paths.
            needles = qt.iter().filter(|t| t.chars().count() >= 4).cloned().collect();
            files = find_files_words(lib, &needles);
        } else {
            files = find_files(lib, &needles);
        }
    }
    if intent == "conflicts" {
        let only: HashSet<String> = mods_named.iter().cloned().collect();
        conflicts = find_conflicts(lib, &only, 20);
    }

    // Ranked answers.
    let mut entries: Vec<Entry> = Vec::new();
    if scope != "mods" {
        entries.extend(builtin().iter().cloned());
        entries.extend(req.extra.iter().take(400).cloned());
    }
    entries.extend(mod_entries(lib));
    let index = Index::build(entries);
    let filter = |e: &Entry| match scope {
        "mods" => e.k == "mod" || e.k == "profile",
        "docs" => e.k == "doc" || e.k == "article",
        _ => true,
    };
    let raw = index.search(&question, &filter);
    // Collapse the two languages of one entry: keep the best score, show the asked language.
    let mut seen: HashMap<String, usize> = HashMap::new();
    let mut cands: Vec<(usize, f64)> = Vec::new();
    for (i, s) in raw {
        let e = index.entry(i);
        let s = s * kind_fits(&intent, &e.k);
        match seen.get(&e.id) {
            Some(&j) => {
                if cands[j].1 < s {
                    cands[j].1 = s;
                }
                if e.lang == lang {
                    cands[j].0 = i;
                }
            }
            None => {
                seen.insert(e.id.clone(), cands.len());
                cands.push((i, s));
            }
        }
    }
    cands.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    cands.truncate(40);
    let top = cands.first().map(|c| c.1).unwrap_or(1.0).max(1e-9);
    let mut hits: Vec<Hit> = cands
        .iter()
        .map(|(i, s)| {
            let e = index.entry(*i);
            Hit { kind: e.k.clone(), id: e.id.clone(), title: e.t.clone(), snippet: snippet(&e.x, &qt, 220), score: s / top, laya: None, action: e.a.clone() }
        })
        .collect();

    // Laya picks the best of the top candidates.
    let mut low_confidence = false;
    if let Some(m) = model {
        if hits.len() >= 2 {
            let k = hits.len().min((tune.top_k as usize).clamp(2, 10));
            let mut crit: Vec<(String, String)> = hits[..k]
                .iter()
                .enumerate()
                .map(|(j, h)| (format!("c{}", j), format!("{} — {}", h.title, h.snippet.chars().take(140).collect::<String>())))
                .collect();
            crit.push(("none".into(), "none of these answers the question".into()));
            let q: LayaQuestion = ("best".into(), "choice", "Which of these parts of the mod manager answers the user's question best?".into(), crit);
            match m.predict(&question, &[q]) {
                Ok(resp) => {
                    let lp = crate::commands::ai_tuning::calibrate(&L::choice_probs(&resp, "best"), tune.temperature);
                    let p_none = lp.iter().find(|(c, _)| c == "none").map(|(_, p)| *p).unwrap_or(0.0);
                    for (j, h) in hits.iter_mut().enumerate().take(k) {
                        let p = lp.iter().find(|(c, _)| *c == format!("c{}", j)).map(|(_, p)| *p).unwrap_or(0.0);
                        h.laya = Some(p);
                        let vote = (p * k as f64 / 2.0).min(1.0);
                        h.score = 0.5 * h.score + 0.5 * vote;
                    }
                    for h in hits.iter_mut().skip(k) {
                        h.score *= 0.5;
                    }
                    hits.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(std::cmp::Ordering::Equal));
                    let mut cand: Vec<f64> = lp.iter().filter(|(c, _)| c != "none").map(|(_, p)| *p).collect();
                    cand.sort_by(|a, b| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));
                    let best = cand.first().copied().unwrap_or(0.0);
                    let second = cand.get(1).copied().unwrap_or(0.0);
                    low_confidence = p_none >= 0.6 || best < tune.threshold || (tune.margin > 0.0 && cand.len() >= 2 && best - second < tune.margin);
                    laya_used = true;
                }
                Err(e) => notes.push(format!("laya:{}", e.chars().take(80).collect::<String>())),
            }
        }
    }
    hits.truncate(limit);
    for h in hits.iter_mut() {
        h.score = (h.score * 1000.0).round() / 1000.0;
        h.laya = h.laya.map(|p| (p * 1000.0).round() / 1000.0);
    }
    if hits.is_empty() && files.is_empty() && conflicts.is_empty() {
        notes.push("nothing_found".into());
    }
    Answer { question, intent, intent_p: (intent_p * 1000.0).round() / 1000.0, routed_by, hits, files, conflicts, laya: laya_used, low_confidence, notes, ms: started.elapsed().as_millis() as u64 }
}

/// Files whose PATH contains the words (« sons moteur » → Sounds/…/Engines/…). Only for
/// questions without a file name.
fn find_files_words(lib: &Library, words: &[String]) -> Vec<FileHit> {
    if words.is_empty() {
        return Vec::new();
    }
    let mut out = Vec::new();
    for m in &lib.mods {
        let mut hits = Vec::new();
        let mut total = 0;
        for f in &m.files {
            let nf = L::fold(&norm_path(f));
            if words.iter().any(|w| nf.contains(w.as_str())) {
                total += 1;
                if hits.len() < 10 {
                    hits.push(f.replace('\\', "/"));
                }
            }
        }
        if total > 0 {
            out.push(FileHit { mod_id: m.id.clone(), mod_name: m.name.clone(), enabled: m.enabled, files: hits, total });
        }
    }
    out.sort_by(|a, b| b.enabled.cmp(&a.enabled).then(b.total.cmp(&a.total)));
    out.truncate(15);
    out
}

/// Mount the engine a caller may use, after its gate: `Ok(provider)` from the AI gate AND the
/// embedded engine installed. Ask never sends a question anywhere, so only the embedded
/// engine counts.
pub fn usable_model<'a>(settings: &ai_core::AiSettings, killed: bool, m: &'a dyn LocalModel) -> Result<&'a dyn LocalModel, &'static str> {
    if killed {
        return Err("killed");
    }
    if !settings.enabled {
        return Err("ai_off");
    }
    if !settings.ask {
        return Err("feature_off");
    }
    if !m.available() {
        return Err("no_model");
    }
    Ok(m)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::Cell;

    fn lib() -> Library {
        Library {
            mods: vec![
                ModInfo { id: "a".into(), name: "Real Engine Sounds".into(), description: "Recorded jet engine sounds".into(), tags: vec!["Sound".into()], enabled: true, files: vec!["Sounds/Effects/Engines/engine.ogg".into(), "Sounds/Effects/Engines/ab.ogg".into(), "README.txt".into()] },
                ModInfo { id: "b".into(), name: "Engine Pack Plus".into(), description: "Other engine sounds".into(), tags: vec![], enabled: true, files: vec!["Sounds\\Effects\\Engines\\engine.ogg".into(), "README.txt".into()] },
                ModInfo { id: "c".into(), name: "Cockpit HD".into(), description: "Textures".into(), tags: vec![], enabled: false, files: vec!["Cockpit/Textures/panel.dds".into(), "README.txt".into()] },
            ],
            profiles: vec![ProfileInfo { id: "p1".into(), name: "Main".into(), game: "DCS".into(), active_count: 2 }],
        }
    }

    /// A model that counts calls: with `None`, Ask must never reach it.
    struct Fake(Cell<usize>, &'static str);
    impl LocalModel for Fake {
        fn available(&self) -> bool {
            true
        }
        fn predict(&self, _t: &str, qs: &[LayaQuestion]) -> Result<Value, String> {
            self.0.set(self.0.get() + 1);
            let mut answers = serde_json::Map::new();
            for (id, _, _, crit) in qs {
                let mut probs = serde_json::Map::new();
                for (k, _) in crit {
                    probs.insert(k.clone(), json!(if k == self.1 { 0.9 } else { 0.1 / crit.len() as f64 }));
                }
                answers.insert(id.clone(), json!({ "type": "choice", "choice": self.1, "probabilities": probs }));
            }
            Ok(json!({ "answers": answers }))
        }
    }

    #[test]
    fn the_builtin_index_is_there_in_both_languages() {
        let b = builtin();
        assert!(b.len() > 500, "ask_index.gen.json is empty or unreadable: {}", b.len());
        assert!(b.iter().any(|e| e.k == "doc" && e.lang == "fr"));
        assert!(b.iter().any(|e| e.k == "command"));
        assert!(b.iter().any(|e| e.k == "article"));
    }

    #[test]
    fn which_mod_modifies_a_file() {
        let a = answer(&Request { question: "Quel mod modifie engine.ogg ?".into(), ..Default::default() }, &lib(), None);
        assert_eq!(a.intent, "files");
        let ids: Vec<&str> = a.files.iter().map(|f| f.mod_id.as_str()).collect();
        assert_eq!(ids.len(), 2);
        assert!(ids.contains(&"a") && ids.contains(&"b"));
        assert!(!a.laya, "no model given: retrieval only");
    }

    #[test]
    fn which_mods_conflict_ignores_readmes() {
        let a = answer(&Request { question: "Quels mods sont en conflit ?".into(), ..Default::default() }, &lib(), None);
        assert_eq!(a.intent, "conflicts");
        assert_eq!(a.conflicts.len(), 1, "{:?}", a.conflicts);
        let c = &a.conflicts[0];
        assert!(c.both_enabled);
        assert_eq!(c.sample, vec!["sounds/effects/engines/engine.ogg".to_string()]);
    }

    #[test]
    fn a_rules_question_finds_the_docs() {
        let a = answer(&Request { question: "c'est quoi le mode jeu ?".into(), lang: "fr".into(), ..Default::default() }, &lib(), None);
        assert_eq!(a.intent, "docs");
        assert!(!a.hits.is_empty());
        let top3: Vec<String> = a.hits.iter().take(3).map(|h| format!("{} {}", h.title, h.snippet).to_lowercase()).collect();
        assert!(top3.iter().any(|t| t.contains("mode jeu") || t.contains("game mode")), "{:?}", top3);
    }

    #[test]
    fn laya_is_only_asked_when_given_and_not_for_decisive_rules() {
        let fake = Fake(Cell::new(0), "c1");
        let a = answer(&Request { question: "how do I share a repo?".into(), ..Default::default() }, &lib(), Some(&fake));
        assert!(a.laya);
        assert_eq!(fake.0.get(), 1, "one rerank question; the intent comes from the rules");
        let fake2 = Fake(Cell::new(0), "none");
        let b = answer(&Request { question: "which mod replaces engine.ogg".into(), ..Default::default() }, &lib(), Some(&fake2));
        assert_eq!(b.routed_by, "rules", "a file name is decisive: no intent question");
    }

    #[test]
    fn a_none_vote_flags_low_confidence() {
        let fake = Fake(Cell::new(0), "none");
        let a = answer(&Request { question: "tell me about the weather on mars".into(), ..Default::default() }, &lib(), Some(&fake));
        if a.hits.len() >= 2 {
            assert!(a.low_confidence);
        }
    }

    #[test]
    fn mods_scope_ranks_only_mods() {
        let a = answer(&Request { question: "engine sounds".into(), scope: "mods".into(), ..Default::default() }, &lib(), None);
        assert!(!a.hits.is_empty());
        assert!(a.hits.iter().all(|h| h.kind == "mod" || h.kind == "profile"));
        assert_eq!(a.hits[0].id, "mod:a");
    }

    #[test]
    fn the_gate_keeps_the_model_out() {
        let fake = Fake(Cell::new(0), "c0");
        let mut s = ai_core::AiSettings::default();
        assert_eq!(usable_model(&s, false, &fake).err(), Some("ai_off"));
        s.enabled = true;
        assert!(usable_model(&s, false, &fake).is_ok());
        assert_eq!(usable_model(&s, true, &fake).err(), Some("killed"));
        s.ask = false;
        assert_eq!(usable_model(&s, false, &fake).err(), Some("feature_off"));
    }
}
